### ISSUE TITLE
Forestry editor - not able to style items

### ISSUE THREAD

**Issue by lawrenced** [esl/elixirconf-eu-jekyll#34]
Cannot style anything in Forestry CMS,

For example, I goto https://app.forestry.io

pages/_speakers-chris-mccord-md/

I try to style the speaker bio, add a list or make a word bold and nothing happens.
Also, the big box on the right that can be edited and styled has no meaning, what am I editing here?

Please investigate and fix.

**Comment by victorldleon** [comment]
I made some testing and for the frontmatter properties and it isn't possible to add any styles  to those properties since they are rendered as text, on the other hand for the **big box on the right** which belongs to the **content** property we can add rich text html tags.

So in this case if you want any property to be edited as rich text we can use the content field instead.
for example we could remove the **bio** property and use the **content** property.
Shall we do this?

**Comment by lawrenced** [comment]
Aha, well done,
could we add the content and the talk details 'abstract' as content?

**Comment by lawrenced** [comment]
Can we add bio as content and add abstract as content too.

**Comment by victorldleon** [comment]
So I already changed the structure to use content.

The correct structure for the speaker Markdown file is this:

```
---
relevance: 10
short_name: bruno-ripa
pic_url: bruno-ripa.jpg
firstname: Bruno
lastname: Ripa
position: Pitching Elixir to a scientific company - Easily finding the right processes to mentor people - See the good practices spread quickly and nicely
twitter: brunoripa
github: brunoripa
---

Bruno Ripa is a software engineer that worked in multiple markets like mobile gaming, big data, digital assets management, analytics, fintech in different places (London, Barcelona, Italy) and with experience in many languages (C/C++, Python, Go, Java, Javascript). He's actually working as an Elixir contractor in the IoT market, primarily focusing on architecture but contributing to infrastructure, deployment, and frontend. If he's not struggling to write any blog post or article he's probably reading about some new tool and/or technology that will cause him to struggle to write about it.
```
And the correct way to structure the talk markdown file is this:

```
---
speaker: bruno-ripa
speaker_name: Bruno Ripa
talk: From the ground to the stars
audience: Beginner
venue: Centrum Konferencyjne, Golden Floor Tower, ul. Chłodna 51, 00-867 Warszawa
event_date: 28 April
from: 11.30 AM
to: 12.30 PM
---

One of the hardest decisions that a startup has to make is which technology stack to adopt in order to maximize productivity, minimize time to market, and also create values like tech culture and vision that naturally become some of the most important company assets. In this talk we'll see why Albora Technologies has adopted Elixir to translate its deep scientific knowledge into a cloud framework to successfully validate the project idea and deliver a disruptive solution in the assets geolocation market.

```

So basically we don't have any **talk information** within the **Speaker** markdown file, since it has been moved to a **Talk markdown file**, we just access to the talk using a for loop  where we filter  the talk by the speaker name

**Comment by bryanhuntesl** [comment]
@lawrenced - is this resolved - I think we brought up the frontmatter vs content stuff before - good learning experience for all concerned - is this resolved now ?
