### ISSUE TITLE
Word Training repeated adinfinitum bug!

### ISSUE THREAD

**Issue by lawrenced** [esl/elixirconf-eu-jekyll#35]
I've added all the speakers that need to be on the website (some don't have photos yet but will soon)
After doing this the word word training is repeating under some of the speakers.

**Comment by victorldleon** [comment]
I verified that and it seems that there's an error importing the MD files because they have mapping values that are not allowed, so once all the MD files are correct it shouldn't be happening

**Comment by victorldleon** [comment]
Doing more testing found out that the MD files are invalid because the special characters are not allowed in the MD files

**Comment by bryanhuntesl** [comment]
@victorldleon - can you clarify and provide an example please?

**Comment by victorldleon** [comment]
Of course @bryanhuntesl by the way this is related to [Issue 34](https://github.com/esl/elixirconf-eu-jekyll/issues/34#issuecomment-575823041)

Example of incorrect:

```
---
short_name: marlus-saraiva
pic_url: marlus-saraiva.jpg
firstname: Marlus
lastname: Saraiva
position: Creator of Broadway - Surface and ElixirSense
talk: Introducing Surface - A new component-based library for Phoenix
audience: Intermediate
**twitter: @MarlusSaraiva**
**github: @msaraiva**
---
abstract: Surface is a new library built on top of Phoenix LiveView that aims to help . . .
```
this is incorrect because it has special characters in the **twitter** and **github** properties, since those characters are not allowed, that file is not loaded and it never reaches the point where it filters the trainings by **short-name**.

So as long as there's not special characters in the frontmatter properties the bug will disappear.
The only place where we can add special characters is in the content section.

Example of correct:

```
---
relevance: 1
short_name: speaker-example
pic_url: https://via.placeholder.com/550
firstname: Speaker
lastname: Example
position: This is an example of how to structure correctly the speaker file according to the current html implementaion.
twitter: speakerexample
github: speakerexample
---

# Heading level 1

## Heading level 2

### Heading level 3

#### Heading level 4

##### Heading level 5

###### Heading level 6

I really like using Markdown.

I think I'll use it to format all of my documents from now on.

This is the first line.  
And this is the second line.

I just love **bold text**.
```
