### ISSUE TITLE
Options for special characters in talk titles

### ISSUE THREAD

**Issue by lawrenced** [esl/elixirconf-eu-jekyll#54]
We have a speaker who's talk is called: 

Elixir + Nerves + keys = Elixir keyboard!

But because the title is in the frontmatter these characters are removed leaving: 

Elixir Nerves Keys Elixir Keyboard

/which doesnt make sense, the speaker has complained about this. 

Can anything be done? Or would it need a rewrite of the site?

**Comment by bryanhuntesl** [comment]
Seeing if this will fix it : https://github.com/esl/elixirconf-eu-jekyll/commit/72b4b2de99f017f7348d06bf37506fbcf5751547

**Comment by lawrenced** [comment]
hmm, talk now seems to have disappeared

**Comment by bryanhuntesl** [comment]
fixed by this [commit]( https://github.com/esl/elixirconf-eu-jekyll/commit/1f34aefb004027cfd4fdf56063f1c5df3ee6b67f) : 

Original issue was that the front-matter didn't contain a title field so the title was being derived from the file name - original [front-matter]( https://github.com/esl/elixirconf-eu-jekyll/commit/72b4b2de99f017f7348d06bf37506fbcf5751547#diff-e73f4bbbeb4bb1adab2fa0dc6116748fL4) here.

We could make that field obligatory in forestry.io in order to ensure such thing doesn't happen in the future.

The behaviour when I changed the file name (bad idea) to include the special characters also worked.
