### ISSUE TITLE
Redirect old conference urls to new ones

### ISSUE THREAD

**Issue by lawrenced** [esl/elixirconf-eu-jekyll#56]
2019 and 2018 still appear in google search first page, clicking on them and getting a 4040 hurts the brand and SEO. There is a way to do a redirect that isnt server side as documented here: https://superdevresources.com/redirects-jekyll-github-pages/ 

We need to redirect:
https://www.elixirconf.eu/elixirconf2015
https://www.elixirconf.eu/elixirconf2016
https://www.elixirconf.eu/elixirconf2017
https://www.elixirconf.eu/elixirconfeu2018
https://www.elixirconf.eu/elixirconfeu2019

to their equivalent years that exist either now as archive.elixirconf.eu/year or as elixirconf.eu/year depending on how the archive section is constructed. Alternatively, at the very least, they need to all redirect to elixirconf.eu

**Comment by bryanhuntesl** [comment]
We've scraped the data from those old sites and got the #19 "develop archive pages" ticket .

Suggest we don't get too complicated here.

Get rid of the old sites - and get cracking building the archive section - the main priority is to provide useful information/the ability to book tickets rather than show of stuff from the past. 

Does it make sense to prioritize that way? The redirects stuff, is just going to confuse matters.

**Comment by lawrenced** [comment]
If this appears too complex for this time then lets put this item on hold?

**Comment by bryanhuntesl** [comment]
Agreed - re-open if necessary. B
